development:
  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: <%= ENV['URL_HOST'] %>
  URL_SCHEMA: http
  SESSION_EXPIRE: 60
  ADMIN: 'admin@puracambio.com'
  TIMEZONE: 'Cairo'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: YOUR_SMTP_PORT
  SMTP_DOMAIN: YOUR_SMTP_DOMAIN
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_USERNAME: YOUR_SMTP_USERNAME
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@yourdomain.com
  SYSTEM_MAIL_FROM: system@yourdomain.com
  SYSTEM_MAIL_TO: group@yourdomain.com
  OPERATE_MAIL_TO: support@yourdomain.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080

  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'


  PUSHER_APP: <%= ENV['PUSHER_APP'] %>
  PUSHER_KEY: <%= ENV['PUSHER_KEY'] %>
  PUSHER_SECRET: <%= ENV['PUSHER_SECRET'] %>
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  COINPAYMENTS_MERCHANT_ID: <%= ENV['COINPAYMENTS_MERCHANT_ID'] %>
  COINPAYMENTS_PUBLIC_API_KEY: <%= ENV['COINPAYMENTS_PUBLIC_API_KEY'] %>
  COINPAYMENTS_PRIVATE_API_KEY: <%= ENV['COINPAYMENTS_PRIVATE_API_KEY'] %>
  COINPAYMENTS_IPN_SECRET: <%= ENV['COINPAYMENTS_IPN_SECRET'] %>
  TWILIO_NUMBER: <%= ENV['TWILIO_NUMBER'] %>
  TWILIO_SID: <%= ENV['TWILIO_SID'] %>
  TWILIO_TOKEN: <%= ENV['TWILIO_TOKEN'] %>

staging:
  URL_HOST: <%= ENV['URL_HOST'] %>
  URL_SCHEMA: <%= ENV['URL_SCHEMA'] %>
  SESSION_EXPIRE: <%= ENV['SESSION_EXPIRE'] %>
  ADMIN: <%= ENV['ADMIN'] %>
  TIMEZONE: <%= ENV['TIMEZONE'] %>

  REDIS_URL: <%= ENV['REDIS_URL'] %>
  TWILIO_NUMBER: <%= ENV['TWILIO_NUMBER'] %>
  TWILIO_SID: <%= ENV['TWILIO_SID'] %>
  TWILIO_TOKEN: <%= ENV['TWILIO_TOKEN'] %>
  SMTP_PORT: <%= ENV['SMTP_PORT'] %>
  SMTP_DOMAIN: <%= ENV['SMTP_DOMAIN'] %>
  SMTP_ADDRESS: <%= ENV['SMTP_ADDRESS'] %>
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  SMTP_AUTHENTICATION: <%= ENV['SMTP_AUTHENTICATION'] %> # could be plain, login or cram_md5

  COINPAYMENTS_MERCHANT_ID: <%= ENV['COINPAYMENTS_MERCHANT_ID'] %>
  COINPAYMENTS_PUBLIC_API_KEY: <%= ENV['COINPAYMENTS_PUBLIC_API_KEY'] %>
  COINPAYMENTS_PRIVATE_API_KEY: <%= ENV['COINPAYMENTS_PRIVATE_API_KEY'] %>
  COINPAYMENTS_IPN_SECRET: <%= ENV['COINPAYMENTS_IPN_SECRET'] %>

  SUPPORT_MAIL: <%= ENV['EMAIL_SUPPORT'] %>
  SYSTEM_MAIL_FROM: n<%= ENV['EMAIL_SYSTEM_FROM'] %>
  SYSTEM_MAIL_TO: <%= ENV['EMAIL_SYSTEM_TO'] %>
  OPERATE_MAIL_TO: <%= ENV['EMAIL_OPERATE_TO'] %>

  WEBSOCKET_HOST: <%= ENV['WEBSOCKET_HOST'] %>
  WEBSOCKET_PORT: <%= ENV['WEBSOCKET_PORT'] %>
#  WEBSOCKET_SSL_KEY: <%= ENV['SSL_KEY'] %>
#  WEBSOCKET_SSL_CERT: <%= ENV['SSL_CERT'] %>

  PUSHER_APP: <%= ENV['PUSHER_APP'] %>
  PUSHER_KEY: <%= ENV['PUSHER_KEY'] %>
  PUSHER_SECRET: <%= ENV['PUSHER_SECRET'] %>
  PUSHER_HOST: <%= ENV['PUSHER_HOST'] %>
  PUSHER_PORT: <%= ENV['PUSHER_PORT'] %>
  PUSHER_WS_PORT: <%= ENV['PUSHER_WS_PORT'] %>
  PUSHER_WSS_PORT: <%= ENV['PUSHER_WSS_PORT'] %>
  PUSHER_ENCRYPTED: <%= ENV['PUSHER_ENCRYPTED'] %>

production:
  URL_HOST: <%= ENV['URL_HOST'] %>
  URL_SCHEMA: <%= ENV['URL_SCHEMA'] %>
  SESSION_EXPIRE: <%= ENV['SESSION_EXPIRE'] %>
  ADMIN: <%= ENV['ADMIN'] %>
  TIMEZONE: <%= ENV['TIMEZONE'] %>

  REDIS_URL: <%= ENV['REDIS_URL'] %>
  TWILIO_NUMBER: <%= ENV['TWILIO_NUMBER'] %>
  TWILIO_SID: <%= ENV['TWILIO_SID'] %>
  TWILIO_TOKEN: <%= ENV['TWILIO_TOKEN'] %>
  SMTP_PORT: <%= ENV['SMTP_PORT'] %>
  SMTP_DOMAIN: <%= ENV['SMTP_DOMAIN'] %>
  SMTP_ADDRESS: <%= ENV['SMTP_ADDRESS'] %>
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  SMTP_AUTHENTICATION: <%= ENV['SMTP_AUTHENTICATION'] %> # could be plain, login or cram_md5

  COINPAYMENTS_MERCHANT_ID: <%= ENV['COINPAYMENTS_MERCHANT_ID'] %>
  COINPAYMENTS_PUBLIC_API_KEY: <%= ENV['COINPAYMENTS_PUBLIC_API_KEY'] %>
  COINPAYMENTS_PRIVATE_API_KEY: <%= ENV['COINPAYMENTS_PRIVATE_API_KEY'] %>
  COINPAYMENTS_IPN_SECRET: <%= ENV['COINPAYMENTS_IPN_SECRET'] %>

  SUPPORT_MAIL: <%= ENV['EMAIL_SUPPORT'] %>
  SYSTEM_MAIL_FROM: <%= ENV['EMAIL_SYSTEM_FROM'] %>
  SYSTEM_MAIL_TO: <%= ENV['EMAIL_SYSTEM_TO'] %>
  OPERATE_MAIL_TO: <%= ENV['EMAIL_OPERATE_TO'] %>

  WEBSOCKET_HOST: <%= ENV['WEBSOCKET_HOST'] %>
  WEBSOCKET_PORT: <%= ENV['WEBSOCKET_PORT'] %>
  #  WEBSOCKET_SSL_KEY: <%= ENV['SSL_KEY'] %>
  #  WEBSOCKET_SSL_CERT: <%= ENV['SSL_CERT'] %>

  PUSHER_APP: <%= ENV['PUSHER_APP'] %>
  PUSHER_KEY: <%= ENV['PUSHER_KEY'] %>
  PUSHER_SECRET: <%= ENV['PUSHER_SECRET'] %>
  PUSHER_HOST: <%= ENV['PUSHER_HOST'] %>
  PUSHER_PORT: <%= ENV['PUSHER_PORT'] %>
  PUSHER_WS_PORT: <%= ENV['PUSHER_WS_PORT'] %>
  PUSHER_WSS_PORT: <%= ENV['PUSHER_WSS_PORT'] %>
  PUSHER_ENCRYPTED: <%= ENV['PUSHER_ENCRYPTED'] %>
