- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.005
  type: WithdrawChannelEther
- id: 800
  key: travelcoin
  currency: tlcp
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.005
  type: WithdrawChannelTravelcoin